# Generated by Django 3.2.5 on 2021-07-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('name_en', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('business_hour', models.CharField(max_length=100)),
                ('closed', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=70)),
                ('pref', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=70)),
                ('street_address', models.CharField(max_length=70)),
                ('website', models.CharField(max_length=250)),
                ('access', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=13)),
                ('fax', models.CharField(max_length=13)),
                ('business_hour_detail', models.CharField(max_length=250)),
                ('closed_detail', models.CharField(max_length=70)),
                ('credit_cards', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('take_out', models.CharField(max_length=70)),
                ('signal', models.CharField(max_length=100)),
                ('facility_services', models.CharField(max_length=100)),
                ('sales_point', models.CharField(max_length=250)),
                ('cancel', models.CharField(max_length=250)),
            ],
        ),
    ]
