# Generated by Django 3.2.5 on 2021-07-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210719_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_hour_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
