# Generated by Django 3.2.5 on 2021-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_business_hour_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closed_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
