# Generated by Django 3.2.5 on 2021-07-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_closed_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cancel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
