# Generated by Django 3.2.5 on 2021-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
