# Generated by Django 3.2.5 on 2021-07-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20210723_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(choices=[('THREE', '三つ星'), ('TWO', '二つ星'), ('ONE', '一つ星'), ('BIB', 'ビブグルマン'), ('TMP', 'ミシュランプレート')], default='BIB', max_length=5),
        ),
    ]
